
DO k:\aplvfp\bsinfo\progs\inicio_trinidad.prg
MODIFY COMMAND k:\aplvfp\bsinfo\progs\cbd_cbdrb011.prg AS 1252
DO k:\aplvfp\bsinfo\progs\cbd_cbdmctas.prg
CLOSE DATABASES all
DO k:\aplvfp\bsinfo\progs\inicio_trinidad.prg
SELECT 0
USE p0012009!cbdrmovm ORDER RMOV01 ALIAS RMOV
SELECT cbdmctas
USE p0012009!cbdmctas ALIAS ctas ORDER ctas01
SELECT auxi
SET ORDER TO AUXI01   && CLFAUX+CODAUX
SELECT 0
USE cia001!cbdppres ALIAS pres
SET ORDER TO PPRE01   && CTAPRE
SELECT 0
USE CBDMTABL ALIAS CCTO ORDER TABL01 AGAIN
SELECT 0
USE p0012009!cbdrmovm ALIAS RMCTO ORDER rmov01 AGAIN
SET FILTER TO INLIST(codcco,'0100','0200','0300','0400','0500')

SELECT RMOV
SET RELATION TO Cbdrmovm.codcta INTO Ctas ADDITIVE
SET RELATION TO clfaux+codaux INTO Auxi ADDITIVE
SET RELATION TO ctapre INTO Pres ADDITIVE
SET RELATION TO '03'+CodCco INTO Ccto ADDITIVE
SELECT AUXI
BROWSE LAST
SELECT CTAS
BROWSE LAST
SELECT PRES
BROWSE LAST
SELECT RMCTO
BROWSE LAST 
SELECT RMOV
SET FILTER TO ("MECANIC"$UPPER(GLODOC) OR "PLANILLA"$UPPER(GLODOC) OR "SUELDO"$UPPER(GLODOC) OR ("LLANTA"$UPPER(GLODOC) OR "LAVADO"$UPPER(GLODOC) OR "MOVILCAR"$UPPER(GLODOC) ) OR "TRACTOR"$UPPER(GLODOC) ) AND codcta='6'SELECT 3
BROWSE LAST

