Dimension AsCodigo(20)
cTit1 = GsNomCia
cTit2 = MES(VAL(XsNroPer),3)
cTit3 = "Usuario : "+TRIM(GsUsuario)
cTit4 = "HABERES FIJOS"
Do Fondo WITH cTit1,cTit2,cTit3,cTit4
*********apertura de archivos************
CLOSE DATA
SELE 6
USE PLNTPERI EXCL ALIAS PERI

ZAP
SET EXCL ON
IF !USED(6)
   CLOSE DATA
   RETURN
ENDIF

SELE 5
DO CASE
   CASE XsCodPln='1'
      USE PLNBLPG1 ORDER BPGO01 ALIAS BPGO
   CASE XsCodPln='2'
      USE PLNBLPG2 ORDER BPGO01 ALIAS BPGO
   CASE XsCodPln='4'
      USE PLNBLPG3 ORDER BPGO01 ALIAS BPGO
ENDCASE
IF !USED(5)
   CLOSE DATA
   RETURN
ENDIF

SELE 4
USE PLNMTABL ORDER TABL01 ALIAS TABL
IF !USED(4)
   CLOSE DATA
   RETURN
ENDIF
*******

IF XsCodPln = "1"
   SELECT 3
   USE PLNTMOV1 ORDER TMOV01 ALIAS TMOV
ENDIF
IF XsCodPln = "2"
   SELECT 3
   USE PLNTMOV2 ORDER TMOV01 ALIAS TMOV
ENDIF
IF XsCodPln = "4"
   SELECT 3
   USE PLNTMOV3 ORDER TMOV01 ALIAS TMOV
ENDIF

IF !USED(3)
   CLOSE DATA
   RETURN
ENDIF
SELE 2
USE PLNDMOVT ORDER DMOV03 ALIAS DMOV
IF !USED(2)
   CLOSE DATA
   RETURN
ENDIF
*******
SELE 1
USE PLNMPERS ORDER PERS01 ALIAS PERS
SET FILTER TO CODPLN=XSCODPLN
GO TOP
IF !USED(1)
   CLOSE DATA
   RETURN
ENDIF
*******
UltTecla = 0
Opcion   = 1
@ 9,10 CLEAR TO 18,67
@ 9,10       TO 18,67
@ 12,23 SAY "Elegir : "
DO WHILE !INLIST(UltTecla,Escape)
	GsMsgKey = "[] [] Posiciona   [Enter] Registrar  [Esc] Salir"
	DO LIB_Mtec with 99
	@ 12,33 GET Opcion FUNCTION '^ Promedio de Comisiones;Traslado de Promedio de Comisiones '
	READ
	UltTecla  = LastKey()
	IF INLIST(UltTecla,Escape,Enter)
		EXIT
	ENDIF
ENDDO
IF UltTecla==Escape
	RETURN
ENDIF
X=0
SELE DMOV
SET ORDER TO DMOV03
SET FILTER TO CODMOV="RB04"
GO TOP
**LLAVE = CODPLN+CODMOV+CODPER+NROPER
**INDICE POR CODPLN+NROPER
* SET ORDER TO DMOV03 = CODPLN+NROPER
GO TOP
DO WHILE !EOF()
	LLAVE = CODPLN+CODPER
	X = 0
	XSCODPER = DMOV.CODPER
	X1=0
	DO WHILE !EOF() AND CODPLN+CODPER = LLAVE
		X = X + 1
		X1=X1+VALCAL
		X2=X1/X
		SKIP
	ENDDO
	IF X > 0
		SELECT PERI
		APPEND BLANK
		replace CODPLN WITH XSCODPLN
		replace NROPER WITH XSNROPER
		replace CODPER WITH XSCODPER
		replace CODMOV WITH "DG01"
		replace VALCAL WITH X2
		replace VALREF WITH 0
		replace FLGEST WITH "R"
	ENDIF
	SELECT DMOV
ENDDO
IF opcion=1
	SELE PERI
	GO TOP
	Largo = 66
	IniPrn=[_Prn0+_PRN5a+chr(Largo)+_Prn5b+_Prn2+_PRN8B]
	xWhile = []
	*XFor   = [VALCAL("@SIT")<5 .AND. VALCAL(XSCODMOV)<>0 ]
	sNomREP = "pln_plnrPCOM"
	DO ADMPRINT WITH "REPORTS"
else
	WAIT WINDOW [Procesando informaci¢n...] NOWAIT
	SELE DMOV
	SET FILTER TO
	SET ORDER TO DMOV02
	SEEK XSCODPLN+XSNROPER+"DG01"
	DELE REST WHILE CODPLN+NROPER+CODMOV=XSCODPLN+XSNROPER+"DG01"
	APPEND FROM PLNTPERI
	WAIT WINDOW [OK] NOWAIT
ENDIF
RETURN
