SELECT Ccbrgdoc.coddoc, Ccbrgdoc.nrodoc, Ccbrgdoc.tpodoc,;
  Ccbrgdoc.fchdoc, Ccbrgdoc.codcli, Ccbrgdoc.nomcli, Ccbrgdoc.coddire,;
  Ccbrgdoc.dircli, Ccbrgdoc.cndpgo, Ccbrgdoc.diavto, Ccbrgdoc.ruccli,;
  Ccbrgdoc.codmon, Ccbrgdoc.tpocmb, Ccbrgdoc.impbto, Ccbrgdoc.pordto,;
  Ccbrgdoc.impdto, Ccbrgdoc.impint, Ccbrgdoc.impgas, Ccbrgdoc.impnet,;
  Ccbrgdoc.impadm, Ccbrgdoc.porigv, Ccbrgdoc.impigv, Ccbrgdoc.imptot,;
  Ccbrgdoc.fchvto, Ccbrgdoc.glodoc, Ccbrgdoc.codref, Ccbrgdoc.nroref,;
  Ccbrgdoc.nroped, Ccbrgdoc.glosa1, Ccbrgdoc.glosa2, Ccbrgdoc.glosa3,;
  Ccbrgdoc.glosa4, Ccbrgdoc.codzon, Ccbrgdoc.codven, Vtaritem.codmat,;
  Vtaritem.desmat, Vtaritem.undvta, Vtaritem.preuni, Vtaritem.canfac,;
  Vtaritem.implin, Vtaritem.facequ, Vtaritem.d1, Vtaritem.d2, Vtaritem.d3,;
  Vtaritem.lote, Vtaritem.fchvto AS fchvtolote, Ccbrgdoc.nroo_c,;
  Ccbrgdoc.tpovta, Ccbrgdoc.impflt, Ccbrgdoc.impseg, Ccbrgdoc.destino,;
  Ccbrgdoc.via, Cbdmauxi.nomaux, Cctcdire.desdire, Vtaritem.prevta;
 FROM ;
     CIA001!ccbrgdoc ;
    LEFT OUTER JOIN CIA001!vtaritem ;
   ON  Ccbrgdoc.coddoc = Vtaritem.coddoc;
   AND  Ccbrgdoc.nrodoc = Vtaritem.nrodoc ;
    INNER JOIN O:\o-negocios\idc\data\p0012022!almcatge ;
   ON  Vtaritem.codmat = Almcatge.codmat ;
    LEFT OUTER JOIN CIA001!cbdmauxi ;
   ON  ( Cbdmauxi.clfaux+Cbdmauxi.codaux ) = ( "VEN"+Ccbrgdoc.codven );
   AND  Ccbrgdoc.codven = Cbdmauxi.codaux ;
    LEFT OUTER JOIN CIA001!cctcdire ;
   ON  ( Cctcdire.clfaux+Cctcdire.codaux+Cctcdire.coddire ) = ( "CLI"+Ccbrgdoc.codcli+Ccbrgdoc.coddire );
   AND  Cctcdire.coddire = Ccbrgdoc.coddire ;
    LEFT OUTER JOIN cia001!vtavpedi ;
   ON  Ccbrgdoc.nroped = Vtavpedi.nrodoc ;
    INNER JOIN cia001!vtarpedi ;
   ON  Vtavpedi.nrodoc = Vtarpedi.nrodoc;
   AND  Vtarpedi.codmat = Almcatge.codant,;
    cia001!vtavcoti ;
    INNER JOIN cia001!vtarcoti ;
   ON  Vtavcoti.nrodoc = Vtarcoti.nrodoc;
   AND  Vtavpedi.nroref = Vtavcoti.nrodoc;
   AND  Vtarcoti.codmat = Almcatge.codref,;
    liq_cob ;
    INNER JOIN liq_det ;
   ON  Liq_cob.liqui = Liq_det.liqui;
   AND  Liq_det.nrodoc = Ccbrgdoc.nrodoc;
 WHERE  ( Ccbrgdoc.coddoc+Ccbrgdoc.nrodoc ) = ( ?_Coddoc+?_NroDoc );
 ORDER BY Ccbrgdoc.tpodoc, Ccbrgdoc.coddoc, Ccbrgdoc.nrodoc