SELECT 0
USE o:\o-negocios\idc\data\cia001\vtavprof.dbf ORDER vpro01 ALIAS vpro
SELECT 0
USE o:\o-negocios\idc\data\cia001\vtarprof.dbf ORDER rpro01 ALIAS rpro
SELECT 0
USE o:\o-negocios\idc\data\cia001\ccbmvtos ORDER vtos03 ALIAS vtos
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2007\cbdvmovm.dbf ORDER vmov01 ALIAS vmov
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2007\cbdrmovm.dbf ORDER rmov01 ALIAS rmov
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2008\cbdvmovm.dbf ORDER vmov01 ALIAS vmov2
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2008\cbdrmovm.dbf ORDER rmov01 ALIAS rmov2
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2009\cbdvmovm.dbf ORDER vmov01 ALIAS vmov3
SELECT 0
USE o:\o-negocios\idc\data\cia001\c2009\cbdrmovm.dbf ORDER rmov01 ALIAS rmov3