USE P0012005!CBDMCTAS IN 0 ALIAS CTAS AGAIN 
USE P0012005!CBDRMOVM IN 0 ALIAS RMOV AGAIN 
SELECT CTAS
SET ORDER TO CTAS01   && CODCTA
SELECT RMOV 
SET ORDER TO RMOV03   && NROMES+CODCTA+CODREF+CODOPE+NROAST 

SCAN 

	=SEEK(CODCTA,'CTAS')
	WAIT WINDOW CODCTA+[ ]+CTAS.NOMCTA+[ ]+NROMES NOWAIT	
	DO CASE 
	
	CASE CTAS.AFTMOV='S' AND (CTAS.MAYAUX='S' OR CTAS.MAYCCO='S')
	
	CASE CTAS.AFTMOV='S' AND CTAS.MAYAUX#'S' AND CTAS.MAYCCO#'S'
		REPLACE CODREF WITH ''
	ENDCASE 	

ENDSCAN

