#define MSG_TIMEOUT		5000
#define MSG_CANCEL		"Operation is canceled."
#define MSG_NOTABLE		"There aren't columns to search."
#define MSG_NOCOLUMN	"There aren't columns to search."
#define MSG_NOTFOUND	"Record isn't found"
#define OPR_CONT		"contain"
#define OPR_EQU			"equal"
#define CPT_LOCATE		"Begin search"
#define CPT_SELECT		"Make selection"
#define CPT_FORM		"Search"
#define CPT_LBL5		"   The tables to search   "
#define CPT_LBL1		"   Selected table's columns   "
#define CPT_LBL3		"Searched text"
#define CPT_LBL4		"Condition"
#define CPT_BTNCONT		"Continue search"
#define CPT_OPTSEL		"Select"
#define CPT_BTNALL		"Show all records"
#define MSG_NOCOLUMN1	"THERE AREN'T COLUMNS"
#define MSG_NOTABLE1	"Table isn't selected."
#define	CPT_FORM1		'Search in form: '